monkey-patch Cheetah's random module name conflict issue
Workaround the problem that Cheetah creates conflicting module names due to
a poor module generator function. Monkey-patch the module with a workaround.

Fixes failures that look like this:

  File "cheetah_DynamicallyCompiledCheetahTemplate_1336479589_95_84044.py", line 58, in _init_
  TypeError: super() argument 1 must be type, not None